name: regression_test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tx:
    uses: ./.github/workflows/regression_template.yml
    with:
      build_script: ./scripts/build_tx.sh
      test_script: ./scripts/test_tx.sh
      cmake_path: ./test/tx/cmake
      result_affix: ThreadX
      skip_deploy: true
  smp:
    uses: ./.github/workflows/regression_template.yml
    with:
      build_script: ./scripts/build_smp.sh
      test_script: ./scripts/test_smp.sh
      cmake_path: ./test/smp/cmake
      result_affix: SMP
      skip_deploy: true
  deploy:
    needs: [tx, smp]
    uses: ./.github/workflows/regression_template.yml
    with:
      skip_test: true
      deploy_list: "ThreadX SMP"
